spring.application.name=Eureka-Service
server.port=8761
# il ne s'enregistre pas lui-même
eureka.client.register-with-eureka=false 
# il ne met pas en cache les clients
eureka.client.fetch-registry=false
