spring.application.name=ConfigServer-service
server.port=8888

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true

# Utiliser les fichiers locaux (native)
spring.cloud.config.server.native.search-locations=classpath:/configs
spring.profiles.active=native